# Generated by Django 5.0.3 on 2024-04-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/catagery/')),
                ('status', models.BooleanField(default=True, help_text='0-hide, 1-show', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/products/')),
                ('status', models.BooleanField(default=True, help_text='0-hide, 1-show', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.catagery', verbose_name='Products')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/products/type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/items')),
                ('quantity', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, help_text='0-hide, 1-show')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trending', models.BooleanField(default=False, help_text='0-hide, 1-show')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.products')),
                ('products_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.type')),
            ],
        ),
    ]
