# Generated by Django 5.0.3 on 2024-04-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0003_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='highlights1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='highlights2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='highlights3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='highlights4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='highlights5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
