# Generated by Django 5.0.3 on 2024-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0004_items_highlights1_items_highlights2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
