# Generated by Django 5.0.3 on 2024-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0005_alter_items_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
