# Generated by Django 5.0.3 on 2024-04-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0006_alter_items_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='products_type',
        ),
        migrations.DeleteModel(
            name='type',
        ),
    ]
